
# Site settings
title: Seikkailuendurol.la
email: seikkailuendurol.la@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kirjoituksia seikkailusta isolla edurolla Keski-Suomen sorateillä ja poluilla.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seikkailuendurol.la" # the base hostname & protocol for your site
twitter_username: seikkailuendurolla
github_username:  seikkailuendurolla

# Build settings
markdown: kramdown

exclude:
  - vendor